-- 为 user_settings 表添加多国家字段
-- 美国字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_profit_rate DECIMAL(5,2) DEFAULT 30.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_weight_rate DECIMAL(10,2) DEFAULT 10.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_volume_factor INTEGER DEFAULT 6000;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_volume_rate DECIMAL(10,2) DEFAULT 8.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_fixed_cost DECIMAL(10,2) DEFAULT 5.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_min_price DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_usd_rate DECIMAL(10,2) DEFAULT 7.20;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_eur_rate DECIMAL(10,2) DEFAULT 7.80;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS us_refund_rate DECIMAL(5,2) DEFAULT 0.00;

-- 德国字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_profit_rate DECIMAL(5,2) DEFAULT 30.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_weight_rate DECIMAL(10,2) DEFAULT 10.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_volume_factor INTEGER DEFAULT 6000;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_volume_rate DECIMAL(10,2) DEFAULT 8.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_fixed_cost DECIMAL(10,2) DEFAULT 5.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_min_price DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_usd_rate DECIMAL(10,2) DEFAULT 7.20;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_eur_rate DECIMAL(10,2) DEFAULT 7.80;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS de_refund_rate DECIMAL(5,2) DEFAULT 0.00;

-- 英国字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_profit_rate DECIMAL(5,2) DEFAULT 30.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_weight_rate DECIMAL(10,2) DEFAULT 10.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_volume_factor INTEGER DEFAULT 6000;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_volume_rate DECIMAL(10,2) DEFAULT 8.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_fixed_cost DECIMAL(10,2) DEFAULT 5.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_min_price DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_usd_rate DECIMAL(10,2) DEFAULT 7.20;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_eur_rate DECIMAL(10,2) DEFAULT 7.80;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gb_refund_rate DECIMAL(5,2) DEFAULT 0.00;

-- 法国字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_profit_rate DECIMAL(5,2) DEFAULT 30.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_weight_rate DECIMAL(10,2) DEFAULT 10.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_volume_factor INTEGER DEFAULT 6000;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_volume_rate DECIMAL(10,2) DEFAULT 8.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_fixed_cost DECIMAL(10,2) DEFAULT 5.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_min_price DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_usd_rate DECIMAL(10,2) DEFAULT 7.20;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_eur_rate DECIMAL(10,2) DEFAULT 7.80;
