ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS fr_refund_rate DECIMAL(5,2) DEFAULT 0.00;

-- 泛欧字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_profit_rate DECIMAL(5,2) DEFAULT 30.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_weight_rate DECIMAL(10,2) DEFAULT 10.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_volume_factor INTEGER DEFAULT 6000;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_volume_rate DECIMAL(10,2) DEFAULT 8.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_fixed_cost DECIMAL(10,2) DEFAULT 5.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_min_price DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_usd_rate DECIMAL(10,2) DEFAULT 7.20;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_eur_rate DECIMAL(10,2) DEFAULT 7.80;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS eu_refund_rate DECIMAL(5,2) DEFAULT 0.00;

-- 添加通用字段（如果不存在）
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS activity_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS ad_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS refund_rate DECIMAL(5,2) DEFAULT 0.00;
